export enum ColumnTypeEnum {
	TINYINT = "tinyint",
    SMALLINT = "smallint",
    MEDIUMINT = "mediumint",
    INT = "int",
    BIGINT = "bigint",
    DECIMAL = "decimal",
    NUMERIC = "numeric",
    FLOAT = "float",
    DOUBLE = "double",
    BIT = "bit",
    BOOL = "bool",
    BOOLEAN = "boolean",
    DATE = "date",
    DATETIME = "datetime",
    TIMESTAMP = "timestamp",
    TIME = "time",
    YEAR = "year",
    CHAR = "char",
    VARCHAR = "varchar",
    BINARY = "binary",
    VARBINARY = "varbinary",
    TINYBLOB = "tinyblob",
    BLOB = "blob",
    MEDIUMBLOB = "mediumblob",
    LONGBLOB = "longblob",
    TINYTEXT = "tinytext",
    TEXT = "text",
    MEDIUMTEXT = "mediumtext",
    LONGTEXT = "longtext",
    ENUM = "enum",
    SET = "set",
    GEOMETRY = "geometry",
    POINT = "point",
    LINESTRING = "linestring",
    POLYGON = "polygon",
    MULTIPOINT = "multipoint",
    MULTILINESTRING = "multilinestring",
    MULTIPOLYGON = "multipolygon",
    GEOMETRYCOLLECTION = "geometrycollection",
    JSON = "json",
}

export enum TailwindColorsEnum {
	SLATE = 'slate',
	GRAY = 'gray',
	ZINC = 'zinc',
	NEUTRAL = 'neutral',
	STONE = 'stone',
	RED = 'red',
	ORANGE = 'orange',
	AMBER = 'amber',
	YELLOW = 'yellow',
	LIME = 'lime',
	GREEN = 'green',
	EMERALD = 'emerald',
	TEAL = 'teal',
	CYAN = 'cyan',
	SKY = 'sky',
	BLUE = 'blue',
	INDIGO = 'indigo',
	VIOLET = 'violet',
	PURPLE = 'purple',
	FUCHSIA = 'fuchsia',
	PINK = 'pink',
	ROSE = 'rose',
}

