version: "3"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 3000
    volumes:
      - ./app:/app/
      - ./ml/model/:/app/ml/model/